CREATE TABLE IF NOT EXISTS channel_settings (
    id varchar,

    label varchar NOT NULL,

    PRIMARY KEY ("id"),
    UNIQUE ("label")
);


INSERT INTO channel_settings (id, label) VALUES
('1tv', 'Первый'),
('2x2', '2X2'),
('boets', 'Боец'),
('che', 'Че'),
('disney', 'Disney'),
('domashniy', 'Домашний'),
('domkino', 'Дом Кино'),
('drive', 'Drive'),
('explorer', 'Explorer'),
('foxlife', 'Fox Life'),
('friday', 'Пятница'),
('ohota', 'Охота и рыбалка'),
('history', 'History'),
('jivi', 'Живи!'),
('karusel', 'Карусель'),
('kuhna', 'Кухня'),
('kultura', 'Культура'),
('matchtv', 'Матч ТВ'),
('khl', 'КХЛ'),
('eurosport', 'Eurosport'),
('discovery', 'Discovery'),
('animalplanet', 'Animal Planet'),
('natgeo', 'Nat Geo'),
('ntv', 'НТВ'),
('otr', 'ОТР'),
('5kanal', 'Пятый'),
('rain', 'Дождь'),
('rbk', 'РБК'),
('reality', 'Reality'),
('ren', 'РЕН'),
('retro', 'Ретро'),
('rossia', 'Россия'),
('ruillusion', 'Русский Иллюзион'),
('sony', 'Sony Channel'),
('sts', 'СТС'),
('tdk', 'ТДК'),
('tlc', 'TLC'),
('tnt', 'ТНТ'),
('tv3', 'ТВ3'),
('tv21', 'ТВ XXI'),
('tv1000', 'TV 1000'),
('tv1000rk', 'TV 1000 Русское кино'),
('tvc', 'ТВЦ'),
('u', 'Ю'),
('usadba', 'Усадьба'),
('zdorovoe', 'Здоровое ТВ'),
('zvezda', 'Звезда');
